# 21.1 Procクラスとは

- `Proc.new {..}` : ブロック `{..}` を保持する `Proc` オブジェクトを生成する
- `proc {..}` : `Proc.new {..}` と同じ

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/hello.rb
Hello, World
Hello, Ruby
```

- `proc.call(args)` : `args` をブロック変数として `proc` に紐づくブロックを呼び出す
- `proc[args]` : `proc.call(args)` と同じ

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/leap.rb
true
false
true
true
```

ブロック変数を `*変数名` の形式で定義すると、引数の数が不定なメソッドと同様に、不定な数の引数を配列で受け取れる

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/proc_args.rb
Array
[2, 4, 6]
Array
[4, 6, 8]
```

デフォルト引数、キーワード引数もブロック変数として定義できる

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/proc_default_and_keyword_args.rb
a: 10
b: 20
c: 30
d: 40
a: 1
b: 2
c: 3
d: 4
```

- `lambda {..}` : ブロック `{..}` を保持する `Proc` オブジェクトを生成する  
    ただし、`Proc.new`、`proc` が生成するオブジェクトと異なり、メソッドのように振る舞う
    - 引数の扱い  
        - `Proc.new` : 多重代入のように扱う
        - `lambda` : 引数の数が異なっているとエラーになる
    - ジャンプ構文の挙動  
        `return`、`next`、`break` の挙動が異なる

        手続き | return | next | break
        --- | --- | --- | ---
        `Proc.new` | 例外が発生する | 手続きオブジェクトを抜ける | 例外が発生する
        `proc` | 例外が発生する | 手続きオブジェクトを抜ける | 例外が発生する
        `lambda` | 手続きオブジェクトを抜ける | 手続きオブジェクトを抜ける | 手続きオブジェクトを抜ける

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/diff_proc_and_lambda_in_args.rb
[1, 2, nil]
Traceback (most recent call last):
	1: from 21.1/diff_proc_and_lambda_in_args.rb:9:in `<main>'
21.1/diff_proc_and_lambda_in_args.rb:6:in `block in <main>': wrong number of arguments (given 2, expected 3) (ArgumentError)
```

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/power_of.rb
125
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/power_of_proc.rb
Traceback (most recent call last):
	1: from 21.1/power_of_proc.rb:8:in `<main>'
21.1/power_of_proc.rb:3:in `block in power_of': unexpected return (LocalJumpError)
```

`Proc.new`、`proc` 内で `break` を呼び出すと、`Proc.new`、`proc` を呼び出したメソッドを抜けようとする  
この例の場合、`power_of` を抜けようとするが、`power_of` を呼び出す処理 `cube = power_of(3)` は終わってしまっているため、エラーが発生する

```
goh@goh ~/s/g/u/enjoyable_ruby> ruby 21.1/prefix.rb
[1, 2, 3]
```

通常のブロックでの `return` の動作は、繰り返しの実行中に、メソッドからいっぺんに戻るような場面で使われるように作られている

```
>> [:a, :b, :c].map do |item|
?> break []
>> end
=> []
```

`break` は「ブロックを受け取ったメソッドの呼び出し元」に戻る

